# Generated by Django 5.0.3 on 2024-03-13 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес организации',
                'verbose_name_plural': 'Адреса организаций',
                'db_table': 'AdressOrg',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Tag URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tag',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Organitathion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('content', models.TextField(verbose_name='Описание организации')),
                ('web_site', models.CharField(max_length=255, verbose_name='Сайт организации')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organitathions.adressorg')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='organitathions.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'Organitathion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=80, null=True, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('to_comment', models.ManyToManyField(blank=True, null=True, related_name='children', to='organitathions.comment', verbose_name='Прикрепить к:')),
                ('organitathion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='organitathions.organitathion', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'Comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=255, verbose_name='Повторите пароль')),
                ('organitathion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organitathions.organitathion')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'Account',
            },
        ),
    ]
