# Generated by Django 5.0.3 on 2024-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organitathions', '0003_remove_comment_parent_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='organitathions.comment', verbose_name='Дочерние комментарии'),
        ),
    ]
