# Generated by Django 5.0.3 on 2024-03-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organitathions', '0005_alter_account_organitathion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organitathion',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organitathions.adressorg', verbose_name='Адрес организации'),
        ),
    ]
